#!/bin/bash

PORT=4000

# GET jwt token
TOKEN=$(curl -X GET http://localhost:$PORT/token |  jq -r '.token')

# TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1NDk4MTc3ODUsInNlc3Npb25faWQiOiJlMzBlZmI5Yi00NzgwLTQ4YTMtOGM3MS02ZjZlMDIyOTRjODYifQ.aumP1PdJGvUPQ82rSB-30Uasf3Q-UETfd8P6Knus0f4B3vyrrikdeC0pnbTdOHmfQ2aX4nzoIXfGe2ekWx_OVQ

# POST tree file, persists new entity
curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: multipart/form-data" -F "treefile=@/home/filip/Dropbox/JavaProjects/spread-server/src/test/resources/continuous/speciesDiffusion.MCC.tre" http://localhost:$PORT/continuous/tree

# DELETE entity
curl -X DELETE -H "Authorization: Bearer $TOKEN" http://localhost:$PORT/continuous/tree

# POST tree file again with the same token
curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: multipart/form-data" -F "treefile=@/home/filip/Dropbox/JavaProjects/spread-server/src/test/resources/continuous/speciesDiffusion.MCC.tre" http://localhost:$PORT/continuous/tree

# POST geojson file
curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: multipart/form-data" -F "geojsonfile=@/home/filip/Dropbox/JavaProjects/spread-server/src/test/resources/geojson/subregion_Australia_and_New_Zealand_subunits.geojson" http://localhost:$PORT/continuous/geojson

# POST geojson file (reupload)
curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: multipart/form-data" -F "geojsonfile=@/home/filip/Dropbox/JavaProjects/spread-server/src/test/resources/geojson/subregion_Australia_and_New_Zealand_subunits.geojson" http://localhost:$PORT/continuous/geojson

# GET attributes
curl -X GET -H "Authorization: Bearer $TOKEN" http://localhost:$PORT/continuous/attributes

echo -e '\n'

# GET hpd-levels
curl -X GET -H "Authorization: Bearer $TOKEN" http://localhost:$PORT/continuous/hpd-levels

echo -e '\n'

# POST hpd-level
curl -X POST -H "Authorization: Bearer $TOKEN" --data "hpd-level=0.80" http://localhost:$PORT/continuous/hpd-level

# POST ycoordinate
curl -X POST -H "Authorization: Bearer $TOKEN" --data "attribute=trait1" http://localhost:$PORT/continuous/coordinates/y

# POST xcoordinate
curl -X POST -H "Authorization: Bearer $TOKEN" --data "attribute=trait2" http://localhost:$PORT/continuous/coordinates/x

# POST external-annotations
curl -X POST -H "Authorization: Bearer $TOKEN" --data "has-external-annotations=true" http://localhost:$PORT/continuous/external-annotations

# POST timescale-multiplier
curl -X POST -H "Authorization: Bearer $TOKEN" --data "timescale-multiplier=0.95" http://localhost:$PORT/continuous/timescale-multiplier

# POST mrsd
curl -X POST -H "Authorization: Bearer $TOKEN" --data "mrsd=2017-04-06" http://localhost:$PORT/continuous/mrsd

# GET model settings
curl -X GET -H "Authorization: Bearer $TOKEN" http://localhost:$PORT/continuous/model

echo -e '\n'

# GET json output
#curl -X GET -H "Authorization: Bearer $TOKEN" http://localhost:$PORT/continuous/output

# echo -e '\n'
