version: "3"
services:

  ipfs-daemon:
    build: ipfs/daemon
    container_name: spread_ipfs-daemon
    volumes:
      - /home/$USER/ipfs-docker:/data/ipfs
      - /home/$USER/ipfs-docker-staging:/export
    networks:
      - ipfs-net

  # ipfs-api:
  #   build: ipfs/api
  #   container_name: spread_ipfs-api
  #   depends_on:
  #     - ipfs-daemon
  #   ports:
  #     - 127.0.0.1:5001:5001
  #   networks:
  #     - ipfs-net

  ipfs-gateway:
    build: ipfs/gateway
    container_name: spread_ipfs-gateway
    depends_on:
      - ipfs-daemon
    ports:
      - 8080:8080
    networks:
      - ipfs-net

  api:
    build: spread-api
    container_name: spread-api
    depends_on:
      - spread-server
    ports:
      - 0.0.0.0:4000:4000
    networks:
      - spread-net

  spread-server:
    image: nodrama/spread-server:latest
    container_name: spread-server
    volumes:
      - /home/$USER/spread-vis:/spread-vis
      - /home/$USER/spread-storage:/spread-storage
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
    depends_on:
      - ipfs-daemon
      # - ipfs-api
      - ipfs-gateway
    networks:
      - ipfs-net
      - spread-net
    # labels:
    #   - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: v2tec/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 300

networks:
  ipfs-net:
    driver: "bridge"
  spread-net:
    driver: "bridge"
